/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.awt.Image;
import java.io.IOException;
import javax.swing.ImageIcon;

/**
 *
 * @author Family
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        ScaleImage();
    }
    private void ScaleImage(){
        ImageIcon icon = new ImageIcon("C:\\Users\\Family\\Documents\\NetBeansProjects\\MMDC_proj\\src\\main\\java\\Forms\\MotorPH Logo.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        label.setIcon(scaledIcon);

    }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HRBtn = new javax.swing.JButton();
        PayrollBtn = new javax.swing.JButton();
        ITBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        TabbedPanel = new javax.swing.JTabbedPane();
        HomeTab = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AccountTab = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        LeaveTab = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        OvertimeTab = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        AttendanceTab = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HRBtn.setBackground(new java.awt.Color(0, 0, 102));
        HRBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HRBtn.setForeground(new java.awt.Color(255, 255, 255));
        HRBtn.setText("Employee Information Management");
        HRBtn.setOpaque(true);
        HRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        PayrollBtn.setBackground(new java.awt.Color(0, 0, 102));
        PayrollBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PayrollBtn.setForeground(new java.awt.Color(255, 255, 255));
        PayrollBtn.setText("Payroll Calculation");
        PayrollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayrollBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PayrollBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 220, -1));

        ITBtn.setBackground(new java.awt.Color(0, 0, 102));
        ITBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ITBtn.setForeground(new java.awt.Color(255, 255, 255));
        ITBtn.setText("Create Account");
        getContentPane().add(ITBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 220, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payrol System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 170, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Account Profile");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Attendance History");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 170, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Apply for Leave");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 170, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Apply for Overtime");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Print Salary");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 470));

        TabbedPanel.setBackground(new java.awt.Color(255, 255, 255));

        HomeTab.setBackground(new java.awt.Color(255, 255, 255));
        HomeTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        HomeTab.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 286, 247));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("MotorPH");
        HomeTab.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Welcome to");
        HomeTab.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        TabbedPanel.addTab("tab1", HomeTab);

        AccountTab.setBackground(new java.awt.Color(255, 255, 255));
        AccountTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Page 2");
        AccountTab.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        TabbedPanel.addTab("tab2", AccountTab);

        LeaveTab.setBackground(new java.awt.Color(255, 255, 255));
        LeaveTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Page 4");
        LeaveTab.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 40, -1));

        TabbedPanel.addTab("tab4", LeaveTab);

        OvertimeTab.setBackground(new java.awt.Color(255, 255, 255));
        OvertimeTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Page 5");
        OvertimeTab.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        TabbedPanel.addTab("tab5", OvertimeTab);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Page 6");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        TabbedPanel.addTab("tab6", jPanel2);

        AttendanceTab.setBackground(new java.awt.Color(255, 255, 255));
        AttendanceTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Page 3");
        AttendanceTab.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        TabbedPanel.addTab("tab3", AttendanceTab);

        getContentPane().add(TabbedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, -30, 470, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void enableHRButtons() {
        HRBtn.setVisible(true);
        PayrollBtn.setVisible(false);
        ITBtn.setVisible(false);
    }
    public void enablePayrollButtons() {
        HRBtn.setVisible(false);
        PayrollBtn.setVisible(true);
        ITBtn.setVisible(false);
    }
    public void enableITButtons() {
        HRBtn.setVisible(false);
        PayrollBtn.setVisible(false);
        ITBtn.setVisible(true);
    }
    public void disableButtons() {
        HRBtn.setVisible(false);
        PayrollBtn.setVisible(false);
        ITBtn.setVisible(false);
    }
    private void HRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HRBtnActionPerformed

    private void PayrollBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayrollBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayrollBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TabbedPanel.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TabbedPanel.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TabbedPanel.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        TabbedPanel.setSelectedIndex(3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        TabbedPanel.setSelectedIndex(4);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        TabbedPanel.setSelectedIndex(5);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountTab;
    private javax.swing.JPanel AttendanceTab;
    public javax.swing.JButton HRBtn;
    private javax.swing.JPanel HomeTab;
    public javax.swing.JButton ITBtn;
    private javax.swing.JPanel LeaveTab;
    private javax.swing.JPanel OvertimeTab;
    public javax.swing.JButton PayrollBtn;
    private javax.swing.JTabbedPane TabbedPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
