/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Classes.Employee;
import Classes.Leave;
import java.awt.Image;
import java.io.IOException;
import javax.swing.ImageIcon;

/**
 *
 * @author Family
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        ScaleImage();
        
    }
    private void ScaleImage(){
        ImageIcon icon = new ImageIcon("C:\\Users\\Family\\Documents\\NetBeansProjects\\MMDC_proj\\src\\main\\java\\Forms\\MotorPH Logo.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        label.setIcon(scaledIcon);

    }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HRBtn = new javax.swing.JButton();
        PayrollBtn = new javax.swing.JButton();
        ITBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        TabbedPanel = new javax.swing.JTabbedPane();
        HomeTab = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AccountTab = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        LeaveTab = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        OvertimeTab = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        AttendanceTab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HRBtn.setBackground(new java.awt.Color(0, 0, 102));
        HRBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HRBtn.setForeground(new java.awt.Color(255, 255, 255));
        HRBtn.setText("Employee Information Management");
        HRBtn.setOpaque(true);
        HRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        PayrollBtn.setBackground(new java.awt.Color(0, 0, 102));
        PayrollBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PayrollBtn.setForeground(new java.awt.Color(255, 255, 255));
        PayrollBtn.setText("Payroll Calculation");
        PayrollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayrollBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PayrollBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 220, -1));

        ITBtn.setBackground(new java.awt.Color(0, 0, 102));
        ITBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ITBtn.setForeground(new java.awt.Color(255, 255, 255));
        ITBtn.setText("Create Account");
        getContentPane().add(ITBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 220, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payrol System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 170, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Account Profile");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Attendance History");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 170, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Apply for Leave");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 170, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Apply for Overtime");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Print Salary");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 470));

        TabbedPanel.setBackground(new java.awt.Color(255, 255, 255));

        HomeTab.setBackground(new java.awt.Color(255, 255, 255));
        HomeTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        HomeTab.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 286, 247));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("MotorPH");
        HomeTab.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Welcome to");
        HomeTab.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        TabbedPanel.addTab("tab1", HomeTab);

        AccountTab.setBackground(new java.awt.Color(255, 255, 255));
        AccountTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        AccountTab.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 120, -1));
        AccountTab.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 120, -1));
        AccountTab.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 120, -1));

        jLabel15.setText("PhilHealth #");
        AccountTab.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));
        AccountTab.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 120, -1));

        jLabel20.setText("Basic Salary");
        AccountTab.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel16.setText("TIN #");
        AccountTab.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jLabel13.setText("Phone #");
        AccountTab.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel19.setText("Position");
        AccountTab.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));
        AccountTab.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 120, -1));

        jLabel5.setText("Birthday");
        AccountTab.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        AccountTab.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 120, -1));

        jLabel9.setText("Last Name");
        AccountTab.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel12.setText("Address");
        AccountTab.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        AccountTab.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 120, -1));
        AccountTab.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 120, -1));

        jLabel17.setText("PagIbig#");
        AccountTab.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel14.setText("SSS");
        AccountTab.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel11.setText("First Name");
        AccountTab.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        AccountTab.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 120, -1));

        jLabel21.setText("Hourly Rate");
        AccountTab.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jLabel10.setText("Employee ID");
        AccountTab.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        AccountTab.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 120, -1));
        AccountTab.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 120, -1));
        AccountTab.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 120, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        AccountTab.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 120, -1));

        TabbedPanel.addTab("tab2", AccountTab);

        LeaveTab.setBackground(new java.awt.Color(255, 255, 255));
        LeaveTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Page 4");
        LeaveTab.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 40, -1));

        TabbedPanel.addTab("tab4", LeaveTab);

        OvertimeTab.setBackground(new java.awt.Color(255, 255, 255));
        OvertimeTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Page 5");
        OvertimeTab.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        TabbedPanel.addTab("tab5", OvertimeTab);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Page 6");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        TabbedPanel.addTab("tab6", jPanel2);

        AttendanceTab.setBackground(new java.awt.Color(255, 255, 255));
        AttendanceTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TabbedPanel.addTab("tab3", AttendanceTab);

        getContentPane().add(TabbedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, -30, 470, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void enableHRButtons() {
        HRBtn.setVisible(true);
        PayrollBtn.setVisible(false);
        ITBtn.setVisible(false);
    }
    public void enablePayrollButtons() {
        HRBtn.setVisible(false);
        PayrollBtn.setVisible(true);
        ITBtn.setVisible(false);
    }
    public void enableITButtons() {
        HRBtn.setVisible(false);
        PayrollBtn.setVisible(false);
        ITBtn.setVisible(true);
    }
    public void disableButtons() {
        HRBtn.setVisible(false);
        PayrollBtn.setVisible(false);
        ITBtn.setVisible(false);
    }
    
    public void setEmployeeDetails(Employee employee) {
    jTextField1.setText(employee.getEmployeeID());
    jTextField2.setText(employee.getFirstName());
    jTextField3.setText(employee.getLastName());
    jTextField4.setText(employee.getBirthday());
    jTextField5.setText(employee.getAddress());
    jTextField6.setText(employee.getPhoneNum());
    jTextField7.setText(employee.getSSS());
    jTextField8.setText(employee.getPhilHealth());
    jTextField9.setText(employee.getTIN());
    jTextField10.setText(employee.getPagIbig());
    jTextField12.setText(employee.getPosition());
    jTextField13.setText(String.valueOf(employee.getBasicSal()));
    jTextField14.setText(String.valueOf(employee.getHourlyRate()));
}
    private void HRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HRBtnActionPerformed

    private void PayrollBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayrollBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayrollBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TabbedPanel.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TabbedPanel.setSelectedIndex(1);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TabbedPanel.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        TabbedPanel.setSelectedIndex(3);
        Leave leave = new Leave();
        LeavePage leavepage = new LeavePage();
        leavepage.setVisible(true);
        leave.setDetails(jTextField2.getText(), jTextField3.getText(), jTextField1.getText());
        leavepage.setDetails(leave.getFirstName(),leave.getLastName(), leave.getEmployeeId());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        TabbedPanel.setSelectedIndex(4);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        TabbedPanel.setSelectedIndex(5);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountTab;
    private javax.swing.JPanel AttendanceTab;
    public javax.swing.JButton HRBtn;
    private javax.swing.JPanel HomeTab;
    public javax.swing.JButton ITBtn;
    private javax.swing.JPanel LeaveTab;
    private javax.swing.JPanel OvertimeTab;
    public javax.swing.JButton PayrollBtn;
    private javax.swing.JTabbedPane TabbedPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField10;
    public javax.swing.JTextField jTextField12;
    public javax.swing.JTextField jTextField13;
    public javax.swing.JTextField jTextField14;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextField8;
    public javax.swing.JTextField jTextField9;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
