package Forms;

import com.opencsv.CSVReader;
import com.opencsv.CSVWriter;
import com.opencsv.exceptions.CsvValidationException;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Classes.Employee;
import Classes.Leave;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ppagd
 */
public class LeavePage extends javax.swing.JFrame {

    /**
     * Creates new form LeavePage
     */
    public LeavePage() {
        initComponents();
        // Manually add action listener to the SubmitLeaveButton

        DateFormat df = new SimpleDateFormat("MM-dd-yyyy");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubmitLeaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        EmployeeFirstName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TypeOfLeave = new javax.swing.JComboBox<>();
        EmployeeLastName = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        LeaveTable = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        LeaveReason = new javax.swing.JPanel();
        LeaveStart = new com.toedter.calendar.JDateChooser();
        LeaveEnd = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        EmployeeIDField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubmitLeaveButton.setBackground(new java.awt.Color(0, 0, 102));
        SubmitLeaveButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SubmitLeaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitLeaveButton.setText("Submit");
        SubmitLeaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitLeaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitLeaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        CancelButton.setBackground(new java.awt.Color(0, 0, 102));
        CancelButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Leave Application Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("First Name");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));
        jPanel5.add(EmployeeFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 150, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Last Name");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Start Date");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("End Date");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Type of Leave");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        TypeOfLeave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sick", "Vacation", "Emergency" }));
        jPanel5.add(TypeOfLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 151, -1));
        jPanel5.add(EmployeeLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, -1));

        LeaveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(LeaveTable);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 230, 220));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Reason");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        javax.swing.GroupLayout LeaveReasonLayout = new javax.swing.GroupLayout(LeaveReason);
        LeaveReason.setLayout(LeaveReasonLayout);
        LeaveReasonLayout.setHorizontalGroup(
            LeaveReasonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LeaveReasonLayout.setVerticalGroup(
            LeaveReasonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel5.add(LeaveReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 400, 80));
        jPanel5.add(LeaveStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 150, -1));
        jPanel5.add(LeaveEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 151, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee ID");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        jPanel5.add(EmployeeIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 150, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 610, 380));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setDetails(String FirstName, String LastName, String EmployeeID) {
        EmployeeFirstName.setText(FirstName);
        EmployeeLastName.setText(LastName);
        EmployeeIDField.setText(EmployeeID);
    }
    private void SubmitLeaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitLeaveButtonActionPerformed
        Leave leave = new Leave();
        DateFormat df = new SimpleDateFormat("MM-dd-yyyy");
        leave.setDetails(EmployeeFirstName.getText(), EmployeeLastName.getText(), EmployeeIDField.getText());

        Date startDate = LeaveStart.getDate();
        Date endDate = LeaveEnd.getDate();

        // Check if the end date is before the start date
        if (endDate.before(startDate)) {
            JOptionPane.showMessageDialog(null, "End leave date cannot be before start leave date.", "Invalid Date Range", JOptionPane.WARNING_MESSAGE);
            return; // Exit the method if the date range is invalid
        }

        try {
            leave.setLeaveType(TypeOfLeave.getSelectedItem().toString());
            leave.setLeaveStart(df.format(startDate));
            leave.setLeaveEnd(df.format(endDate));

            if (leave.leaveValidity()) {
                leave.RecordLeave();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LeavePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LeavePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CsvValidationException ex) {
            Logger.getLogger(LeavePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(LeavePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SubmitLeaveButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeavePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeavePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeavePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeavePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField EmployeeFirstName;
    private javax.swing.JTextField EmployeeIDField;
    private javax.swing.JTextField EmployeeLastName;
    private com.toedter.calendar.JDateChooser LeaveEnd;
    private javax.swing.JPanel LeaveReason;
    private com.toedter.calendar.JDateChooser LeaveStart;
    private javax.swing.JTable LeaveTable;
    private javax.swing.JButton SubmitLeaveButton;
    private javax.swing.JComboBox<String> TypeOfLeave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
